
//Firebase --------------------------------

export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';

export const
	REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
export const
	FIREBASE_PASSWORD_RESET_EMAIL = 'FIREBASE_PASSWORD_RESET_EMAIL';
	
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';

export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';

export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';

export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';

export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';


//Like Button --------------------------------
export const LIKE_BUTTON_INCREMENT = 'LIKE_BUTTON_INCREMENT';

export const LIKE_BUTTON_DECREMENT = 'LIKE_BUTTON_DECREMENT';

//Play Nine --------------------------------

export const 	CHANGE_NUMBER_OF_STARS = 'CHANGE_NUMBER_OF_STARS';

export const SELECT_NUMBER = 'SELECT_NUMBER';

export const UNSELECT_NUMBER = 'UNSELECT_NUMBER';

export const CHECK_ANSWER = 'CHECK_ANSWER';
